app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(stocks = "MSFT")
app$setInputs(stocks = c("MSFT", "AAPL"))
app$setInputs(stocks = c("MSFT", "AAPL", "OOG"))
app$setInputs(stocks = c("MSFT", "AAPL"))
app$setInputs(stocks = c("MSFT", "AAPL", "OO"))
app$setInputs(stocks = c("MSFT", "AAPL"))
app$setInputs(stocks = c("MSFT", "AAPL", "GOOG"))
app$setInputs(stocks = c("MSFT", "AAPL", "GOOG", "SPY"))
app$setInputs(stocks = c("MSFT", "AAPL", "GOOG", "SPY", "FB"))
app$setInputs(stocks = c("MSFT", "AAPL", "GOOG", "SPY", "FB", "TSLA"))
app$setInputs(stocks = c("MSFT", "AAPL", "GOOG", "SPY", "FB", "TSLA", "WMT"))
app$setInputs(stocks = c("MSFT", "AAPL", "GOOG", "SPY", "FB", "TSLA", "WMT", "AAL"))
app$setInputs(stocks = c("MSFT", "AAPL", "GOOG", "SPY", "FB", "TSLA", "WMT", "AAL", "JBLU"))
app$setInputs(stocks = c("MSFT", "AAPL", "GOOG", "SPY", "FB", "TSLA", "WMT", "AAL", "JBLU", "VNQ"))
app$setInputs(stocks = c("MSFT", "AAPL", "GOOG", "SPY", "FB", "TSLA", "WMT", "AAL", "JBLU", "VNQ", "VO"))
app$setInputs(investment = 10000)
app$setInputs(factor = c(0.88, 1.68))
app$setInputs(click = "click")
app$snapshot()
